name: nexus_admin
description: Caramel Cottage admin console for the web.
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  go_router: ^18.0.1
  intl: ^0.20.3
  nexus_core:
    path: ../../packages/core
  nexus_data:
    path: ../../packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
