name: nexus_admin
description: Caramel Cottage admin console for the web.
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  nexus_core:
    path: ../../packages/core
  nexus_data:
    path: ../../packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
